defaults: True
extends: null
# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md013.md
MD013:
  # Number of characters
  line_length: 180
  # Number of characters for headings
  heading_line_length: 180
  # Number of characters for code blocks
  code_block_line_length: 180
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

// rules:
//   indentation:
//     spaces: 2
//     indent-sequences: consistent
//   line-length:
//     max: 180
//     allow-non-breakable-words: true
//     allow-non-breakable-inline-mappings: false
//   trailing-spaces: enable
//   new-lines:
//     end-of-file: newline
//   key-ordering: disable
//   document-start: disable
//   document-end: disable
//   comments: disable
//   empty-lines: disable
//   truthy: enable
