// extends: default

rules:
  indentation:
    spaces: 2
    indent-sequences: consistent

  line-length:
    max: 180
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false

  trailing-spaces: enable

  new-lines:
    end-of-file: newline

  key-ordering: disable

  document-start: disable
  document-end: disable

  comments: disable
  empty-lines: disable

  truthy: enable
