name: YAML Lint

on: [push]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run markdownlint
      uses: nosborn/github-action-markdown-cli@v3.3.0
      with:
        files: 'source'
        ignore_files: 'source/docs/sample.md'
        config_file: .markdownlint.yml
